version: '3.9'

services:
  auth-service:
    container_name: auth-service
    image: vendee-cinema/auth-service:dev
    build:
      context: .
      dockerfile: .dockerfile
    restart: always
    env_file:
      - .env.production.local
    expose:
      - '9101'
    volumes:
      - ../logs/auth:/var/log/services/auth
    networks:
      - vendee-cinema

networks:
  vendee-cinema:
    external: true
